---
- name: configure web server
  hosts: servera.lab.example.com
  tasks:
    - name: Include environment task file
      include_tasks: tasks/environment.yml
      vars:
        package: httpd
        service: httpd
    - name: import firewall
      import_tasks: tasks/firewall.yml
      vars:
        firewall_pkg: firewalld
        firewall_svc: firewalld
        rule:
          - http
          - https
    - name: import placeholder task
      import_tasks: tasks/placeholder.yml
      vars:
        file: /var/www/html/index.html
- name: import test play
  import_playbook: plays/test.yml
  vars:
    url: "http://servera.lab.example.com"