---
- name: installing and configuring apache
  hosts: all
  become: true
  vars_files: ./variable_file.yml
  tasks:
    - name: installing apache
      dnf:
        name: "{{ var_module }}"
        state: latest
    - name: copying webpage
      copy:
        src: ./tempo.html
        dest: /var/www/html/index.html
    - name: configuring firewall
      firewalld:
        port: 9999/tcp
        permanent: true
        state: enabled
      notify: reload firewall
    - name: replacing port no in vars_file
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80$'
        replace: 'Listen 9999'
    - name: configuring selinux
      seport:
        ports: 9999
        proto: tcp
        setype: "{{ se_service }}"
        state: present
    - name: reloading apache
      service:
        name: httpd
        enabled: yes
        state: restarted
  handlers:
    - name: reload firewall
      service:
        name: firewalld
        state: restarted
- name: testing
  hosts: all
  tasks: 
    - name: testing apache
      uri:
        url: http://172.25.250.10:9999
        status_code: 200