- name: add a text to existing file
  hosts: all
  remote_user: root
  tasks: 
    - name: Add a single line of text to a file
      lineinfile:
        path: /home/devops/users.txt
        line: This file was added by the lineinfile module.
        state: present
        