---
# tasks file for lvm/

- name: create partition 
  parted:
    device: "{{ device_name }}"
    number: "{{ num_part }}"
    part_start: "{{ item-1 }}GiB"
    part_end: "{{ item }}GiB" 
    state: present
    label: gpt
    resize: true
  when: item <= "{{ num_part }}"
  loop: 
    - 2
    - 3
    - 4
  when: partion == true
- name: setting filesystem
  filesystem:
    fstype: "{{ fs_type }}"
    dev: "{{ item }}"
  loop: "{{ dev }}"
  when: file_system == true
- name: create physical volume
  lvg:
    vg: "{{ vg_name }}"
    pvs: "{{ dev }}"
    state: present
  when: physical_volume == true
- name: create volume group
  lvg:
    vg: "{{ vg_name }}"
    pvs: "{{ dev }}"
    state: present
  when: volume_group == true
- name: create logical volume
  lvol:
    vg: "{{ vg_name }}"
    lv: logical_volume
    size: "{{ vg_size }}G"
    state: present
  when: logicalVg == true